[package]
name = "structs"
version = "0.1.0"
authors = ["Przemyslaw Kot <przemyslaw.kot@snom.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
